server:
  port: 8200

spring:
  application:
    name: order-simulator-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.microservices.ordersimulator: DEBUG