server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**
          filters:
            - AddRequestHeader=X-Gateway-Token, microservices-internal-2024
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AddRequestHeader=X-Gateway-Token, microservices-internal-2024
        - id: order-simulator-service
          uri: lb://order-simulator-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AddRequestHeader=X-Gateway-Token, microservices-internal-2024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: microservices-secret-key-2024-very-long-secret-key-for-jwt-token-generation

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.microservices.apigateway: DEBUG